name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      BASE_API_PATH: https://api.github.com/repos/${{ github.repository }}/

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Build with Gradle Wrapper
      run: chmod a+rwx gradlew; ./gradlew build

